### ISSUE TITLE
RichRequest.remoteAddress does not account for multiple IP addresses in X-Forwarded-For header

### ISSUE THREAD

**Issue by JustAHappyKid** [scalatra/scalatra#1032]
The `X-Forwarded-For` header can include multiple IP addresses, separated by commas. For example, it might include a value like `1.2.3.4, 9.8.7.6`.

In these cases, `remoteAddress` should probably just return the left-most IP address (`1.2.3.4` in given example), if I'm understanding [the convention](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) correctly.

**Comment by takezoe** [comment]
Hm, that is perhaps right. However, that will be incompatible change. I'm considering adding new method which returns `X-FORWARDED-FOR` header value as it is (comma-separated multiple addresses) and deprecate the current `remoteAddress`. In addition, `remoteAddresses: Seq[String]` can be added.

What do you think of this idea?

**Comment by magnolia-k** [comment]
The current remoteAddress method will return the result of the getRemoteAddr method if X-FORWARDED-FOR is not specified.

The method itself that does this behavior is useful and necessary.

Adding a new method is one idea, but since the current behavior itself is wrong (multiple IP addresses are returned as a single String when X-FORWARDED-FOR is specified), I think we can incorporate it as an incompatible change in a major version upgrade ( Scalatra 3.0?)

Translated with www.DeepL.com/Translator (free version)

**Comment by takezoe** [comment]
I think even Scalatra 2.8 won't be released within a short time frame. Changing it in Scalatra 2.8 might be acceptable.

**Comment by JustAHappyKid** [comment]
@takezoe, I think your recommendation (add `remoteAddresses` method) is a big improvement over the current situation.

Having `remoteAddress` return something that is not a valid IP address is a bit of a land-mine. In our case, we were attempting to store it in a "`clicks`" table, and the only reason I noticed the issue was because we occasionally get a user with two IPs in `X-Forwarded-For`, leading to a database exception.

**Comment by takezoe** [comment]
OK, let's add `remoteAddresses` anyway in 2.7.2. A remaining problem is which version we'll fix `remoteAddress` behavior, 2.7.2 or 2.8.0? I'm feeling it might be better to fix in 2.7.2 with adding `remoteAddresses` for clarity of changes even though it's an incompatible changes. Making these changes separately will be a little confusing.
