### ISSUE TITLE
NotFound returns 200 instead of 404

### ISSUE THREAD

**Issue by orlandojsjr** [scalatra/scalatra#554]
I'm using org.scalatra.NotFound as result of an action. 
With parameter: 

> NotFound("some value") returns 404

Without parameter:

> NotFound  returns 200

Is it correct?

issue-related: https://github.com/scalatra/scalatra/issues/390

**Comment by verto** [comment]
The problem is that you didn't call NotFound with (), it's important to execute the apply of NotFound object where it return an ActionResult instance. see it: https://github.com/scalatra/scalatra/blob/2.4.x/core/src/main/scala/org/scalatra/ActionResult.scala#L132-L134 

So, when you just write "NotFound", the action return value is an object where it's rendered like a simple string value.

**Comment by takezoe** [comment]
Close because this is not a bug of Scalatra.
