### ISSUE TITLE
scalatra_2.11 2.5.0 Unsupported major.minor version 52.0 on jdk 7

### ISSUE THREAD

**Issue by imre-kerr** [scalatra/scalatra#608]
Scalatra 2.5.0 seems to have been built for jdk 8. Is this intended? If so, the documentation should reflect this.

**Comment by futurechimp** [comment]
Hi Imre, 

I've just updated the installation docs, thanks for pointing it out.

Cheers, 
Dave

**Comment by futurechimp** [comment]
I've just noticed that the 2.5 docs branch isn't showing up yet, working to resolve this.

**Comment by yohanakh** [comment]
Is there a way to make Scalatra 2.5.0 work JDK 7 ? This is important to me. Thanks

**Comment by xuwei-k** [comment]
> Is there a way to use Scalatra 2.5.0 with JDK 7 ?

There is no ways. dropped JDK 7 support since scalatra 2.5.x

**Comment by futurechimp** [comment]
There is already a notice in the `2.5` branch that Scalatra 2.5 requires JDK 8, I think: 

https://github.com/scalatra/scalatra-website/blob/2.5/getting-started/installation.md

The problem is that scalatra.org is still showing the 2.4 documentation (it's set up as a set of git branches on the server and needs to be changed there).

There are several ways to fix it:

1. just update the 2.4 branch with the correct install instructions - easiest to do but all the 2.5-related stuff in the rest of the site will still be a problem. 
1. switch the branch on the server to show 2.5 docs by default. This is a simple but crappy fix, as we want to retire this server so Ivan can stop paying for it.
1. review the `gh-pages` branch, publish it to Github pages, and re-point the scalatra.org DNS. I've moved the whole site into a new Hugo blog. 

The third option is preferable but I'm only chipping away at it slowly. I may find time to deal with it tonight.

**Comment by xuwei-k** [comment]
http://scalatra.org/getting-started/installation.html

![screen shot 2017-06-04 at 1 50 41](https://cloud.githubusercontent.com/assets/389787/26755441/435aa89c-48c8-11e7-8fed-7f2bdadb006d.png)

**Comment by takezoe** [comment]
We've updated scalatra.org for Scalatra 2.5. It describes Scalatra 2.5 requires Java8 as @xuwei-k indicated.
