### ISSUE TITLE
404 for installation and first project!

### ISSUE THREAD

**Issue by aadrian** [scalatra/scalatra#634]
The most important links on the first page ```README.markdown``` for **new users** deliver 404:
 - http://www.scalatra.org/2.5/getting-started/installation.html
 - http://www.scalatra.org/2.5/getting-started/first-project.html

Version 2.5 seems to be since November last year out, but the main site http://scalatra.org/ still seems to have no links to it (except the news).

Thank you.

**Comment by evan-wehi** [comment]
Also the 2.4 versions and links without version numbers and many other links as well.

**Comment by xuwei-k** [comment]
https://github.com/scalatra/scalatra-website/issues/126

**Comment by takezoe** [comment]
Fixed in #642

**Comment by evan-wehi** [comment]
Guides are there but the layout is a mess. Items repeated 4 teams with a date of January 1 0001

http://scalatra.org/guides

**Comment by aadrian** [comment]
@evan-wehi this seems to be a Hugo https://www.gohugo.io/ problem:
   - all urls **without** slashes, e.g. http://scalatra.org/guides have this problem
   - all urls **with** slashes work correctly, e.g. http://scalatra.org/guides/

**Comment by takezoe** [comment]
This is not a hugo problem.

Category index pages is generated by hugo automatically for url without tail `/`, and guides contain 4 Scalatra versions (2.2, 2.3, 2.4 and 2.5) under `guides/` directory, so same name pages are listed up 4 times. And since article date is not specified in these pages, date is displayed as January 1 0001. They are correct behavior in hugo.

I added `/` to end of links in the top page. The web site is now deploying.

**Comment by aadrian** [comment]
@takezoe see my comment on gitter https://gitter.im/scalatra/scalatra?at=58dc408a408f90be666cb450 . The report shows further dead links.

**Comment by takezoe** [comment]
@aadrian Thanks. I will check it later. or pull request is welcome :-)

**Comment by aadrian** [comment]
@takezoe From that pastebin report is visible that some variables were not replaced correctly. E.g. ```{{site.examples}}``` and ```{{site.baseurl}}``` since they're present in the final links.
