### ISSUE TITLE
Empty request.body when stream has already been consumed

### ISSUE THREAD

**Issue by rossabaker** [scalatra/scalatra#73]
This happens:
1. On POSTs with content-type is `application/x-www-form-urlencoded`.  Scalatra's call to getParameter consumes the servlet input stream.  See 3.1.1 of the Servlet spec for more details.
2. On repeated invocations to request.body.  It consumes the servlet input stream without caching the result.

This issue is [discussed in more detail](http://groups.google.com/group/scalatra-user/browse_thread/thread/940a632095e236a8) on the Google group.

**Comment by acrisci** [comment]
+1

I don't use this header in my api because I always assume post bodies are json. Now it seems I have to make a special exception to always reject `application/x-www-form-urlencoded` content type because getting the request body won't work correctly.

Otherwise, it will be very confusing to curl clients, because this content type is used by default when `-d <data>` is given on the command line. Without the exception, they will get a 400 with a message like "empty request body" instead of the true message which should be "invalid content type". But the latter error is artificial because I don't use that header at all.

Are there any good workarounds for this?

**Comment by acrisci** [comment]
Here is a hacky workaround I came up with that seems to be working so far. Use this function to get the request body in a robust way.

```scala
  def requestBody(): String = {
    val contentLength = request.contentLength.getOrElse(-1).toString.toInt
    request.contentType.getOrElse("") match {
      case "application/x-www-form-urlencoded" =>
        if (contentLength < 1) "" else params.keys.head
      case _ =>
        request.body
    }
  }
```

**Comment by magnolia-k** [comment]
There seems to be no way to solve this problem at once (this problem has not changed even with the specification of servlet 4.0), but I thought that it was better to describe it in the API document, so I made a PR.

https://github.com/scalatra/scalatra/pull/782

**Comment by magnolia-k** [comment]
There is no solution beyond adding to the document, so close it.
