### ISSUE TITLE
Why the client can not connect to the server?

### ISSUE THREAD

**Issue by ghost** [scalatra/scalatra#890]
Hi all 
Would be nice if someone could help me https://stackoverflow.com/questions/55190367/why-the-client-can-not-connect-to-the-server 

Thanks

**Comment by treaz** [comment]
As commented in the stackoverflow thread:
your question is missing important bits of information: 

- What makes you think that this issue is related to scalatra&atmosphere? 
- What happens when you try to use a different WebSockets client? 
- Can you share a demo project that anyone can download and see the error that you're seeing? - What libs&versions are you using?

**Comment by treaz** [comment]
Also, why raise an issue here when you're not sure yet whether the problem is in the WS client or the WS server?

**Comment by treaz** [comment]
@takezoe can we close this issue?

**Comment by takezoe** [comment]
@treaz Thanks for handling this. We can close this issue since no feedback from the inquirer.
